"""What a scenario needs from storage, expressed without naming an engine.

The debt stage 2 left on purpose. Usecases talk to repositories directly today,
which is why `core.usecases` is still outside the independence contract, and the
reason it waited is that a repository port is a UnitOfWork — a transaction and
`SET LOCAL app.user_id` — and both are Postgres-shaped questions that would have
been answered blind against SQLite.

**Why a UnitOfWork rather than one port per repository.** Two writes that must
land together are the whole reason: registration binds a number to a chat and
then writes the orders behind it, and a crash between them today leaves a
customer registered with an empty history. One repository per port would give
each its own connection and its own commit, which is exactly the shape that
cannot express "both or neither".

**Why `user_id` sits on the unit and not on every method.** It is what Postgres
turns into `SET LOCAL app.user_id` at the start of the transaction, and RLS
policies read it from there. Passing it per call would mean every method could
disagree with every other, and the one that forgot would be the one that
returned somebody else's rows. `None` is the worker's service context: no user,
no policy filtering, and deliberately hard to write by accident.
"""
from __future__ import annotations

from types import TracebackType
from typing import Protocol, runtime_checkable

from core.domain.broadcast import Job
from core.domain.offer import Offer
from core.domain.phone import VerifiedPhone
from core.domain.referral import Earned
from core.domain.stock import Waiting


@runtime_checkable
class OrderCache(Protocol):
    """The orders a customer can be shown."""

    async def upsert(self, user_id: int, rows: list[dict]) -> None:
        """Write orders, keeping the more authoritative source's values.

        Rows come from core.domain.order_row. merge_key and source_rank are
        derived by the implementation and never accepted from a caller — that
        is how unrelated orders once collapsed onto one row.
        """
        ...


@runtime_checkable
class UserProfiles(Protocol):
    """The people the bot knows about.

    Two operations, not one, and the split is the point. Binding a number
    decides whose orders a chat can see; filling in a name does not. Merging
    them into one `save(user_id, phone, name, email)` was the first shape of
    this port, and it forced the caller that only had a name to produce a phone
    — which, since the phone must be a VerifiedPhone, meant either wrapping a
    string from the database back into a proof it no longer had, or weakening
    the type for everybody. Two methods cost one line and keep the guarantee
    where it means something.
    """

    async def bind_phone(self, chat_id: int, phone: VerifiedPhone) -> int:
        """Attach an ownership-verified number to a chat. Returns the person's id.

        The only write that changes who a chat is. VerifiedPhone all the way
        down to the repository on purpose: this is the last place the proof
        still exists, and the write it guards is the one that would hand a
        stranger somebody else's order history.

        **Why this returns an id, and why it alone takes a chat_id.** Under
        Postgres a person has a surrogate `users.id` minted by the database,
        while `tg_chat_id` is merely unique — revision 001 says so out loud:
        "an artefact of one messenger, and the person behind it can get a new
        one". Every other method here, and `user_id` on the unit itself,
        therefore means that surrogate.

        It comes from here because this is the only operation that *can* create
        a person: `users.phone_normalized` is NOT NULL and UNIQUE with no
        default, so no row can exist before a number is verified. There is no
        "create the user, bind the phone later" to model, and identity is
        generated by the repository rather than invented by a caller.

        Under SQLite the surrogate and the chat id are the same number, so the
        implementation returns what it was handed and nothing changes.
        """
        ...

    async def update_profile(
        self,
        user_id: int,
        *,
        full_name: str | None = None,
        email: str | None = None,
    ) -> None:
        """Fill in what the CRM knows about an already-bound user.

        Best-effort enrichment, and it must never be able to change the phone —
        which is why the phone is not a parameter rather than being an optional
        one nobody passes.
        """
        ...


@runtime_checkable
class UnitOfWork(Protocol):
    """One transaction, and the repositories that share it.

    Used as an async context manager. Leaving the block without commit() rolls
    back — the default has to be the safe one, because the path that forgets is
    always the exceptional path.
    """

    orders: OrderCache
    users: UserProfiles

    async def __aenter__(self) -> "UnitOfWork": ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    """How a scenario gets a unit without knowing which engine is under it.

    `user_id=None` is the service context — the worker syncing orders for people
    who have not registered — and it is spelled explicitly so that reaching it
    is a decision rather than an omission.
    """

    def __call__(self, *, user_id: int | None = None) -> UnitOfWork: ...


@runtime_checkable
class OfferCache(Protocol):
    """What the shop sells, as we last managed to read it.

    A cache and nothing more: the storefront is the authority, this is what a
    screen can answer from without waiting on it. Written whole by the hourly
    sweep, read a handful of skus at a time by the screens that offer to buy
    something.

    **Deliberately not on the UnitOfWork above.** The unit exists for two writes
    that must land together and for `SET LOCAL app.user_id`, and the sweep has
    neither. It is one write, and it belongs to nobody: `offers` has no user
    column and no policy to read an identity from, so the only honest `user_id`
    for it is None. Hanging it off the unit would hand every scenario that opens
    a unit *for a person* a repository that person must never be near, and would
    make the one table that is deliberately shared look like part of somebody's
    transaction.

    It is therefore passed to the scenario the way `Storefront` already is — an
    argument, not something reached through a factory. There is no second write
    to be atomic with, so there is nothing for a factory to hold.
    """

    async def record(self, offers: dict[str, Offer]) -> None:
        """Write these offers down, one row per sku, leaving the rest standing.

        **Per sku, never the whole table.** Skus absent from `offers` keep the
        values they had. The feed is paginated, and a short read is
        indistinguishable from a shrunken catalogue — a method that deleted what
        it had not seen would give one truncated page the power to unpublish
        products. It is the same reason `Storefront.get_offers` is documented to
        answer {} for a failure rather than a partial picture.

        **An empty mapping writes nothing.** The scenario already refuses to
        call this with {}; this line says the implementation must refuse too.
        The rule protects the whole catalogue from a single 500, and one guard
        for it is one more than can be deleted by a refactor that looks correct.

        **A mapping is taken, and the key is not read.** The parameter is what
        `Storefront.get_offers` returns rather than an iterable, because the
        moment two ports on one path disagree about the shape, the scenario
        between them grows a loop whose only purpose is to re-key data that
        arrived keyed. What each row is written under is `offer.sku` — the
        values are what an implementation reads.

        The two agree by construction: one parse builds the mapping and puts
        the same sku on the offer inside it. Which one wins is said out loud
        anyway, because it is the difference between a caller re-keying the
        mapping to rename an offer and a caller doing that while nothing
        happens.

        Returns nothing, deliberately. What the sweep logs is what it read, not
        what the table now holds; reading a count back would answer a question
        nobody asked, at the price of a full scan every hour.
        """
        ...


@runtime_checkable
class StockSnapshot(Protocol):
    """What availability looked like the last time we looked.

    Not `core.ports.catalog.StockLevels`, and the resemblance is worth spelling
    out because the two are one word apart. That port is the shop's own answer,
    read over the network on every poll; this one is our memory of the previous
    answer. A restock exists only in the difference between them, which is why
    comparing them is domain code (`core.domain.stock.restocked`) and all this
    port does is remember and recall.

    Not on the UnitOfWork for the usual reason: the snapshot belongs to nobody
    and has no second write to land with.
    """

    async def last_seen(self) -> dict[str, int]:
        """sku -> units free to sell, as recorded by the previous sweep.

        Empty means nothing has ever been recorded — first run, fresh database —
        and the scenario reads it as "write the baseline, tell nobody", because
        otherwise the whole catalogue looks like it just came back. Telling that
        apart from a failed read is deliberately not this port's problem: a
        failed read is caught upstream, where the catalogue port answers {} and
        the sweep stops before reaching storage at all.
        """
        ...

    async def remember(self, levels: dict[str, int]) -> None:
        """Replace the memory with what was just read.

        A whole snapshot, not a delta, because a delta has no way to say that a
        sku left the catalogue. An empty snapshot writes nothing: a sweep that
        came back with no numbers must not erase the baseline the next one is
        compared against, or the poll after that announces a restock of the
        entire shop.
        """
        ...


@runtime_checkable
class RestockWatchlist(Protocol):
    """The people holding a promise: tell me when this one is back.

    Separate from StockSnapshot even though one sweep uses both, because they
    are not the same kind of fact. The snapshot is the poller's own memory,
    replaceable on every poll and worth nothing if lost. This is something a
    customer asked the bot for, and the asymmetry decides who may write what:
    the sweep replaces the snapshot wholesale and may only ever *release*
    entries here, never create them. Subscribing is a screen's business and is
    not in this port for that reason.

    Keyed by `chat_id`, not by the surrogate `users.id` the unit speaks — see
    the identity rule in core/ports/users.py. It is named `chat_id` on `Waiting`
    precisely so the difference cannot be misread as agreement.
    """

    async def waiting_for(self, skus: list[str]) -> list[Waiting]:
        """Everyone waiting on any of these skus — one row per person per sku.

        Flat, not grouped by chat, and that is not laziness. One sku can have
        many people behind it and one person can be waiting on several skus that
        return in the same sweep; deciding that this becomes one message per
        person rather than a burst is the scenario's call, and a port returning
        a mapping would have made it already.

        An empty list of skus returns nothing rather than everybody.
        """
        ...

    async def release(self, fulfilled: list[tuple[int, str]]) -> None:
        """Drop the (chat, sku) promises that have now been kept.

        Called before the message has actually been sent, and that is
        deliberate: the promise is "tell me when it is back", once. Keeping the
        rows until delivery would have the next sweep queue them again for
        anybody whose message is still in the queue, and the dedup key that
        stops that is cheaper than the state machine that would otherwise be
        needed.
        """
        ...


@runtime_checkable
class ReferralLedger(Protocol):
    """What a recommendation has earned, and the row that says it was paid once.

    Not on the UnitOfWork, and this one has two reasons rather than the usual
    one. `referrals` is not among the twelve tables in Alembic revision 001, so
    there is no transaction to join yet; and the sweep's two writes are
    deliberately *not* atomic — the row goes down first so that a crash before
    the message is queued costs somebody a thank-you rather than paying them
    twice. Wrapping the pair in a unit would quietly reverse that choice, which
    is a decision about money and not a decision about ports.

    Only what the sweep does. `referral_counts` — how many this person invited,
    and how many of those have ordered — stays a plain function in
    core/repos/referrals.py, because its caller is the invite screen and screens
    still import repositories. It gets a read port on the day the
    handlers-see-ports-only contract is uncommented, driven by the screen that
    asks rather than by the table that exists.
    """

    async def earned(self, prefix: str, limit: int) -> list[Earned]:
        """Friends who arrived through a link, have since ordered, unpaid.

        The owner's rule lives inside this one question: a friend counts once
        she has an order that was not cancelled, because opening a bot costs
        nothing and a programme that pays for that pays for nothing. It is one
        question rather than three — read the arrivals, read their orders, check
        what has been paid — because a scenario assembling that answer itself
        would be a sweep holding two tables open to decide one thing.

        `prefix` is how `users.source` spells "brought by": the referrer's chat
        id follows it. Pulling the id back out is the implementation's business,
        and the prefix arrives from the caller rather than living here because
        it is a deep link the bot owns and the entry point already passes it
        down.

        `limit` carries no default, for the same reason `KnownBirthdays.to_ask`
        carries none: how much one round costs is the sweep's policy, and a
        default here would be a second place where it is decided.

        Unrewarded only. A referral already in the ledger never comes back from
        this, which is what makes the sweep safe to run every quarter of an
        hour.
        """
        ...

    async def record_reward(
        self, friend_chat_id: int, referrer_chat_id: int
    ) -> bool:
        """Claim this referral for payment. False if it was already claimed.

        The boolean is the claim itself, not a report about it: a caller that
        ignored it would pay a second time on the next run. That is why this is
        one call and not "ask, then write" — between the asking and the writing
        there is room for the other sweep, and on Postgres there will be a
        second process to put in it.

        Called before the message is queued, deliberately, and the scenario says
        so at the call site too. The other order pays twice whenever the process
        dies in between; being thanked late is the better of the two failures.
        """
        ...

    async def record_code(self, friend_chat_id: int, code: str) -> None:
        """Record which code paid for this referral.

        A separate write rather than an argument to the claim above, because it
        happens afterwards: the row has to exist before anything is sent, while
        the code is only known to have been handed over once the message
        carrying it is queued. There is no code at all until the shop creates
        one — the message then says a person will write, and this is not called.

        Nothing in the running system reads it back yet; it is what somebody
        auditing the programme will ask for, and it is written at the moment the
        answer is still true.
        """
        ...


@runtime_checkable
class BroadcastJournal(Protocol):
    """What was sent, by whom, and whether the send is over.

    Deliberately small, because the queue already answers most of what used to
    be asked here. Outcomes per message — sent, blocked, failed, still waiting —
    are `MessageQueue.campaign_totals`, and the recipient snapshot is the queued
    rows themselves. `broadcast_targets` was all three at once, written for one
    feature, and stage 6 replaced it rather than adapting it. What is left is
    the header: a text a person typed, an author, and a status that gives a
    campaign an end.

    Not on the UnitOfWork, and here the second reason is worth more than the
    first. `broadcast_jobs` is not among the twelve tables in revision 001; but
    also the header is written *before* the messages are queued, on purpose, so
    that a crash in between leaves a job whose campaign is empty — which the
    sweep then closes with zeros and a summary saying nothing went out. One
    transaction over both would erase that state and the handling written for
    it.
    """

    async def record(self, text: str, admin_id: int) -> int:
        """Write the header down and return the job's id.

        The id becomes the campaign — `bcast.<job id>` — so a send on Tuesday
        and a send on Wednesday are two campaigns in the funnel rather than one
        bucket called "broadcast". That is why this hands the number back
        instead of writing and forgetting: the caller cannot queue anything
        until it knows which campaign it is queueing into.
        """
        ...

    async def unfinished(self) -> list[Job]:
        """Jobs still marked running, oldest first.

        Not a resume list, and the distinction is what stage 6 bought: nothing
        needs resuming when the messages are rows in a queue that outlives the
        process. This is read by the sender's loop — the thing already awake —
        to notice which jobs have drained.

        The order is part of the contract. The oldest running job is the one
        somebody has been waiting longest to hear about, and a caller that
        reported them in whatever order the engine liked would look
        intermittently broken for exactly the jobs people remember.
        """
        ...

    async def finish(self, job_id: int) -> None:
        """Close the job out.

        After this the job stops coming back from `unfinished()`, which is the
        whole point: a job left running is one that gets checked on every pass
        of the sender's loop, forever.
        """
        ...
